- README.md
- lib/dnsimple.js
- test/dnsimple.spec.js
Closes #6 
I've also made sure that the format is the same as in other clients.
I've also wondered if there is a better way of handling the version of the client so we don't have to update the default `User-Agent` and the corresponding tests.
> Correctly handle custom User-Agent header

- package.json
This is just a simple PR to include the `files` property in the `package.json` so that npm will only install the necessary files.
> only include lib folder when publishing from npm

- lib/dnsimple/registrar.js
- test/dnsimple/registrar.spec.js
The registrar methods were using our old, URLs that we decided to migrate before API v2 GA.
This PR updates the URLs to the public, [documented](https://developer.dnsimple.com/v2/registrar/) ones.
See dnsimple/dnsimple-developer#147
> Update registrar URLs

- .travis.yml
- CHANGELOG.md
- README.md
- lib/dnsimple.js
- package-lock.json
- package.json
Updates Node to the current version and configures Travis to run a build for each supported Node version.
Because of the `lodash` vulnerability, we have to move to the latest maintenance Node. 
Travis builds are enough for this
1. Create tag:
```
git tag -a v3.0.0 -s -m "Release 3.0.0"
git push origin --tags
```
2 . Run `npm publish` to push the new version out.
> Release 3.0.0

- CHANGELOG.md
- lib/dnsimple.js
- package.json
Bump to 3.0.1. Dependency on `npm` has been removed.
> Release 3.0.1

- lib/dnsimple.js
In Node.js v13 this value has been changed to `0`. Hardcoding it to previous value will preserve behavior under Node.js v13
Closes #25
> Hardcode default timeout to 120000

- CHANGELOG.md
- lib/dnsimple/registrar.js
- test/dnsimple/registrar.spec.js
- test/fixtures.http/cancelDomainTransfer/success.http
- test/fixtures.http/getDomainTransfer/success.http
This commit introduces two client methods for the new features in
TransferAPI:
- getDomainTransfer - Retrieves the information for a specific domain
transfer
- cancelDomainTransfer - Cancels an in progress domain transfer
> Implement client methods for Transfer API

- test/dnsimple/domains.spec.js
- test/dnsimple/registrar.spec.js
- test/dnsimple/webhooks.spec.js
- test/fixtures.http/cancelDomainTransfer/success.http
- test/fixtures.http/createDomain/created.http
- test/fixtures.http/getDomain/success.http
- test/fixtures.http/getDomainTransfer/success.http
- test/fixtures.http/listDomains/success.http
- test/fixtures.http/registerDomain/success.http
- test/fixtures.http/renewDomain/success.http
- test/fixtures.http/transferDomain/success.http
We deprecated expires_on attribute in our app and docs in favor of
expires_at. This commit introduces the new field in Domain response and
also updates fixtures with the new expires_at and the one that removed 
premium_price.
> Introduce expires_at for Domain and update fixtures

- CHANGELOG.md
- test/dnsimple/certificates.spec.js
- test/fixtures.http/getCertificate/success.http
- test/fixtures.http/issueLetsencryptCertificate/success.http
- test/fixtures.http/issueRenewalLetsencryptCertificate/success.http
- test/fixtures.http/listCertificates/success.http
- test/fixtures.http/purchaseLetsencryptCertificate/success.http
- test/fixtures.http/purchaseRenewalLetsencryptCertificate/success.http
We deprecated expires_on attribute in our documentation and api in
favor of expires_at. This commit introduces the new field in Certificate
response and also updates some fixtures.
> Introduce expires_at for Certificate and update fixtures

- CHANGELOG.md
- lib/dnsimple.js
- package-lock.json
- package.json
Dependencies have updated: `nock` and `semistandard`.
This bumps to version 4.2.1.
> Release 4.2.1

- .travis.yml
- CHANGELOG.md
- LICENSE.txt
- package-lock.json
- package.json
This PR:
- NEW: Adds NodeJS v16 to Travis build
- NEW: Adds NodeJS node (latest) to Travis build (with regular builds this helps us raise future incompatibilities)
- CHANGED: Moves lockfileVersion to v2
Also move Travis build to use Ubuntu 20.04 (focal)
> Adds NodeJS v16 to Travis

- .travis.yml
- CHANGELOG.md
- README.md
- package.json
As NodeJS v10 is now EOL, we bump the minimum required version to v12
> Bumps minimum NodeJS version required to v12

- .github/workflows/release.yml
- CONTRIBUTING.md
Adds the automated release workflow.
When a new tag is pushed the release workflow will pick it up and start the releasing of the new version.
Things that need to be done (configuration wise), which I have no access to (we need someone with admin rights on this repo for that):
> Adds the release workflow

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- package.json
As NodeJS v12 reached EOL, we are bumping minimum version to v14, plus adding to v18 to CI
re https://nodejs.org/en/about/releases/
> Bumps minimum NodeJS version required to v14 and adds NodeJS v18

- lib/dnsimple/certificates.js
- test/dnsimple/certificates.spec.js
We no longer require a contact_id to be provided to be able to purchase a Lets Encrypt certificate.
> No longer require `contact_id` to purchase LetsEncrypt certificates

- CHANGELOG.md
- lib/dnsimple/client.js
- test/dnsimple/contacts.spec.js
- test/fixtures.http/createContact/error-validation-errors.http
This PR:
- Adds a new test that verifies that the client will parse validation errors produced by the API into the rejected promise output of the client.
- Adds a getter method in error objects to access any validation errors if present
> Review validation errors in HTTP 400 API responses

- lib/dnsimple/registrar.js
- package-lock.json
- package.json
- test/dnsimple/registrar.spec.js
- test/testUtils.js
Implement the `getDomainRegistration` and `getDomainRenewal` API methods.
We're starting to test the library in a new way, by testing the network request only, as our library does not handle responses for each method specifically, so current response tests do not test actual code. For example, we generically deserialise all responses into an untyped object and do not actually map and validate fields, which is standard JS. Currently, we also don't sync the fixtures, so our tests don't reflect the actual current API schema.
We will test this by using `sinon` to mock the client request function to ensure that the network requests exactly match. Our plan is to slowly migrate existing tests towards this model.
> Implement getDomainRegistration and getDomainRenewal APIs

- CHANGELOG.md
- lib/accounts.ts
- lib/certificates.ts
- lib/contacts.ts
- lib/domains.ts
- lib/identity.ts
- lib/main.ts
- lib/registrar.ts
- lib/secondary_dns.ts
- lib/services.ts
- lib/templates.ts
- lib/tlds.ts
- lib/types.ts
- lib/vanity_name_servers.ts
- lib/webhooks.ts
- lib/zones.ts
- test/certificates.spec.ts
- test/contacts.spec.ts
- test/domain_delegation_signer_records.spec.ts
- test/services.spec.ts
- test/zone_records.spec.ts
- test/zones.spec.ts
This moves common types (e.g. response data) to `types.ts` with names to allow them to be easily used and referenced from user code. Values of enums are also provided for stricter better type checking and autocomplete.
We export them directly at the package level instead of a submodule as it's not possible to import in a nested fashion in TS or JS. We do not have many exports at the package level anyway, so this is safe. We don't require directly importing from the file as we don't want to make the file path part of our public API. Therefore, types can be imported from user code as such:
```
import { Account, Certificate } from "dnsimple";
```
> Extract TypeScript types to separate file and declare enum type values

- CHANGELOG.md
- lib/zones.ts
- test/fixtures.http/activateZoneService/success.http
- test/fixtures.http/deactivateZoneService/success.http
- test/zones.spec.ts
This PR implements https://github.com/dnsimple/dnsimple-developer/pull/502 which allows for the management of DNS resolution for a particular zone.
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/3
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/2
> Add support to activate and deactivate DNS services for a zone

- CHANGELOG.md
- lib/main.ts
- lib/registrar.ts
- lib/types.ts
- test/fixtures.http/checkRegistrantChange/success.http
- test/fixtures.http/createRegistrantChange/success.http
- test/fixtures.http/deleteRegistrantChange/success.http
- test/fixtures.http/getRegistrantChange/success.http
- test/fixtures.http/listRegistrantChanges/success.http
- test/registrar_registrant.spec.ts
This PR introduces 5 new endpoints that are part of the domain contact management API that was introduced in https://github.com/dnsimple/dnsimple-developer/pull/501.
The following endpoints have been added:
- **listRegistrantChanges**: GET `/{account}/registrar/registrant_changes`
- **createRegistrantChange**: POST `/{account}/registrar/registrant_changes`
- **checkRegistrantChange**: POST `/{account}/registrar/registrant_changes/check`
- **getRegistrantChange**: GET `/{account}/registrar/registrant_changes/{registrantchange}`
- **deleteRegistrantChange**: DELETE `/{account}/registrar/registrant_changes/{registrantchange}`
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1729
> Add support for registrant APIs

- CHANGELOG.md
- lib/types.ts
- test/fixtures.http/getZone/success.http
- test/fixtures.http/listZones/success.http
- test/zones.spec.ts
This PR adds [missing attributes](https://github.com/dnsimple/dnsimple-developer/pull/542) of the Zone response:
- `secondary`, `last_transferred_at`, `active` to `Zone` type
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/17
> Add missing attributes to the Zone API responses

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
In this PR:
- Remove NodeJS 14, 16, and 19 (all currently at EoL)
- Add NodeJS 20 LTS
> Update NodeJS runtime requirements

- test/domain_email_forwards.spec.ts
- test/fixtures.http/createEmailForward/created.http
- test/fixtures.http/deleteEmailForward/success.http
- test/fixtures.http/getEmailForward/success.http
- test/fixtures.http/listEmailForwards/success.http
See https://github.com/dnsimple/dnsimple-developer/issues/315 for reference
The Node API client doesn't define models for the data structures used as input or output of DNSimple's API endpoints. Therefore, no actual changes are required.
In this PR:
- Minor housekeeping
> Update `EmailForward` fields

- .github/workflows/ci.yml
- CHANGELOG.md
- LICENSE.txt
- README.md
- lib/domains.ts
The changes to go out in the next version (9.0.0) are:
- NEW: Add support for node 22.x
- CHANGED: `DomainCollaborators` have been deprecated and will be removed in the next major version. Please use our Domain Access Control feature.
- CHANGED: Updated dependencies
Belongs to https://github.com/dnsimple/dnsimple-engineering/issues/231
> Patch cycle - 2024 / Cycle 5
